theme: alembic-jekyll-theme

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

title: Uwe's Blog
description: >
  **Uwe L. Korn**, Data Scientist, Music Hacker and Food lover.
copyright: Uwe L. Korn
sass:
  sass_dir: assets/sass
url: https://uwekorn.com
twitter_username: "xhochy"
github_username:  "xhochy"
feed_icon: rss
paginate_path: "/page/:num/"
paginate: 5
highlighter: rouge

timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title:
    output: true
    description:
    feature_text: |
      ## Uwe's Blog
      My writing about data engineering, opensource development, general
      programming and thoughts about engineering culture.
    feature_image: "https://picsum.photos/2560/600?image=1026&blur"

# 6. Jekyll collections settings
defaults:
  -
    feature_image: "https://picsum.photos/2560/600?image=1026&blur"
    scope:
      path: ""
    values:
      layout: page
      image: "https://avatars2.githubusercontent.com/u/70274?s=460&v=4" # Default image for sharing

navigation_header:
  - title: Home
    url: /
  - title: Projects
    url: /projects.html
  - title: About Uwe
    url: /cv.html
  - title: Talks
    url: /talks.html
  - title: Github
    url: https://github.com/xhochy
  - title: Twitter
    url: https://twitter.com/xhochy

navigation_footer:
  - title: RSS Feed
    url: /rss.xml
  - title: Imprint
    url: /imprint.html
